version: 2.1

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#next-gen-circleci-go-image
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
      - run: make
  release:
    docker:
      - image: cimg/base:2020.01
    steps:
      steps:
      - checkout
      - run: >
      - run: curl -vkL -o - https://github.com/intuit/auto/releases/download/v9.21.0/auto-linux.gz | gunzip > ~/auto
      - run: chmod a+x ~/auto
      - run: ~/auto shipit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - release:
          requires:
            - build
          filters:
            branches:
              only: master
